const topics = {
    'Housing': 'Determinants of health',
    'Equality and diversity': 'Leadership and workforce',
    'Integrated care': 'Health and care services',
    'Patient involvement': 'Patients and the public',
    'Patient experience': 'Patients and the public',
    'Technology and data': 'Technology and innovation',
    'Public health': 'Determinants of health',
    'General election 2019': 'Policy, finance and performance',
    'Health inequalities': 'Determinants of health',
    'NHS finances': 'Policy, finance and performance',
    'Performance': 'Policy, finance and performance',
    'Mental health': 'Health and care services',
    'Health and Care Act 2022': 'Policy, finance and performance',
    'Social care finances': 'Health and care services',
    'Productivity': 'Policy, finance and performance',
    'NHS five year forward view': 'Policy, finance and performance',
    'Governance and regulation': 'Policy, finance and performance',
    'Commissioning and contracting': 'Policy, finance and performance',
    'Volunteers': 'Patients and the public',
    'Public opinion': 'Patients and the public',
    'Population health': 'Determinants of health',
    'Carers': 'Patients and the public',
    'Workforce and skills': 'Leadership and workforce',
    'Voluntary and community sector': 'Unknown',
    'System leadership': 'Leadership and workforce',
    'Sustainability and transformation plans': 'Health and care services',
    'Quality improvement': 'Policy, finance and performance',
    'Organisational culture': 'Leadership and workforce',
    'Covid-19': 'Health and care services',
    'Clinical leadership': 'Leadership and workforce',
    'New models of care': 'Health and care services',
    'Hospital care': 'Health and care services',
    'General practice': 'Health and care services',
    'Emergency care': 'Health and care services',
    'Community services': 'Health and care services',
    'Adult social care': 'Health and care services',
    'Long-term conditions': 'Health and care services',
    'NHS long-term plan': 'Policy, finance and performance',
    'General election 2015': 'Policy, finance and performance',
    'Local service design': 'Health and care services',
    'Patient leadership': 'Patients and the public',
    'Competition, markets and choice': 'Policy, finance and performance',
    'End-of-life care': 'Health and care services',
    'Cancer services': 'Health and care services',
    'Brexit': 'Unknown',
    'Access to care': 'Health and care services',
    'Devolution': 'Policy, finance and performance',
    'General election 2017': 'Policy, finance and performance',
    'Patient safety': 'Patients and the public',
    'Older people': 'Patients and the public',
    'Better Care Fund': 'Health and care services',
    'Health and Social Care Act 2012': 'Policy, finance and performance',
    'Children and young people': 'Patients and the public',
    'Sexual health care': 'Health and care services',
    'Health and wellbeing boards': 'Health and care services',
    'Maternity services': 'Health and care services',
    'Clinical commissioning groups': 'Health and care services'
};

const processedTopics = {
    housing: 'Determinants of health',
    'equality and diversity': 'Leadership and workforce',
    'integrated care': 'Health and care services',
    'patient involvement': 'Patients and the public',
    'patient experience': 'Patients and the public',
    'technology and data': 'Technology and innovation',
    'public health': 'Determinants of health',
    'general election 2019': 'Policy, finance and performance',
    'health inequalities': 'Determinants of health',
    'nhs finances': 'Policy, finance and performance',
    performance: 'Policy, finance and performance',
    'mental health': 'Health and care services',
    'health and care act 2022': 'Policy, finance and performance',
    'social care finances': 'Health and care services',
    productivity: 'Policy, finance and performance',
    'nhs five year forward view': 'Policy, finance and performance',
    'governance and regulation': 'Policy, finance and performance',
    'commissioning and contracting': 'Policy, finance and performance',
    volunteers: 'Patients and the public',
    'public opinion': 'Patients and the public',
    'population health': 'Determinants of health',
    carers: 'Patients and the public',
    'workforce and skills': 'Leadership and workforce',
    'voluntary and community sector': 'Unknown',
    'system leadership': 'Leadership and workforce',
    'sustainability and transformation plans': 'Health and care services',
    'quality improvement': 'Policy, finance and performance',
    'organisational culture': 'Leadership and workforce',
    'covid-19': 'Health and care services',
    'clinical leadership': 'Leadership and workforce',
    'new models of care': 'Health and care services',
    'hospital care': 'Health and care services',
    'general practice': 'Health and care services',
    'emergency care': 'Health and care services',
    'community services': 'Health and care services',
    'adult social care': 'Health and care services',
    'long-term conditions': 'Health and care services',
    'nhs long-term plan': 'Policy, finance and performance',
    'general election 2015': 'Policy, finance and performance',
    'local service design': 'Health and care services',
    'patient leadership': 'Patients and the public',
    'competition, markets and choice': 'Policy, finance and performance',
    'end-of-life care': 'Health and care services',
    'cancer services': 'Health and care services',
    brexit: 'Unknown',
    'access to care': 'Health and care services',
    devolution: 'Policy, finance and performance',
    'general election 2017': 'Policy, finance and performance',
    'patient safety': 'Patients and the public',
    'older people': 'Patients and the public',
    'better care fund': 'Health and care services',
    'health and social care act 2012': 'Policy, finance and performance',
    'children and young people': 'Patients and the public',
    'sexual health care': 'Health and care services',
    'health and wellbeing boards': 'Health and care services',
    'maternity services': 'Health and care services',
    'clinical commissioning groups': 'Health and care services'
}

const hash = {}
for (const topic in topics) {
    if (!hash.hasOwnProperty(`${topic.toLowerCase()}`)) {
        hash[`${topic.toLowerCase()}`] = topics[topic]
    }
}

module.exports = {
    topics, processedTopics
}
